config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: "callbacks", registrations: 'users/registrations' }
  root 'welcome#index'

  resources :recipes do
    resources :notes
  end

  match 'search(/:search)', :to => 'recipes#index', :as => :search, via: [:get, :post]
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients, inverse_of: :recipe, :dependent => :destroy
  has_many :notes, inverse_of: :recipe, :dependent => :destroy

  belongs_to :user

  validates_presence_of :name, :message => "Please fill in a title"

  accepts_nested_attributes_for :ingredients, :allow_destroy => true

  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
  end

  def calculate_cost
    self.ingredients.map { |i| i['unit_price'] }.reduce(:+)
  end

  def calculate_portion_cost
    (calculate_cost / self.quantity).round(2) if self.quantity
  end
end

app/controllers/recipes_controller.rb
require 'will_paginate/array'

class RecipesController < ApplicationController
  respond_to :html, :js

  def index
    @recipes = current_user.recipes.search(params[:search]).order(updated_at: :desc)
  end

  def new
    @recipe = Recipe.new
    4.times { @recipe.ingredients.build }
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      @recipe.update_attribute(:cost, @recipe.calculate_cost)
      redirect_to @recipe
    else
      render :new
    end
  end

  def show
    @recipe = current_user.recipes.find(params[:id])
    @notes = @recipe.notes.order(updated_at: :desc)
    @portion_cost = @recipe.calculate_portion_cost
  end

  def edit
    @recipe = current_user.recipes.find(params[:id])
  end

  def update
    @recipe = current_user.recipes.find(params[:id])
    if @recipe.update_attributes(recipe_params)
      @recipe.update_attribute(:cost, @recipe.calculate_cost)
      redirect_to @recipe
    end 
  end

  def destroy
    @recipe = current_user.recipes.find(params[:id])
    @recipe.destroy
    flash[:notice] = 'Recipe successfully deleted'
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :quantity, ingredients_attributes: [:id, :name, :amount, :price, :size, :unit_price, :amount_unit_of_measurement, :size_unit_of_measurement, :_destroy])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.slim
section.container
  .row
    .col-md-8.col-md-offset-2
      - if @recipe.errors.any?
        .errors-div
          h4 Please fill in all fields
      h1 What would you like to call your recipe?
      br
      = form_for @recipe do |f|
        .form-group
          = f.text_field :name, class: 'form-control', required: true
          br
          br   
          i.fa.fa-chevron-down.fa-4x.chevron-anchor-recipes

          div class=('hidden-field' unless is_edit?)
            h2 Now add some ingredients
            br

            = f.fields_for :ingredients do |f|
              = render 'ingredient_fields', f: f
            .span
              = link_to_add_association '<i class="fa fa-plus-circle fa-lg rotate"></i> Add another ingredient'.html_safe, f, :ingredients
            .text-center.submit-button
              = f.submit "#{button_text} recipe", class: 'button'

.chocolate
  = image_tag('chocolate-1.png')

app/views/recipes/_ingredient_fields.html.slim
.form-inline
  .nested-fields
    .field
      = f.text_field :name, class: 'form-control ingredient-name', placeholder: "Ingredient", required: true, title: "Name of ingredient"

      = f.number_field :amount, step: :any, min: 0, class: 'form-control form-control-inline ingredient-amount', placeholder: "Quantity", required: true, value: (number_with_precision(f.object.amount, precision: 0)), title: "How much you used"

      = f.select :amount_unit_of_measurement, [['g','g'],['kg','kg'],['ml','ml'],['l','l'],['oz','oz'],['lb','lb'],['tsp','tsp'],['tbsp','tbsp'],['pint','pint'],['each','unit']], {prompt: 'Unit'}, {required: 'true', autofocus: 'true', class: 'form-control form-control-inline dropdown', placeholder: "g", title: "Unit of measurement"}

      = f.number_field :price, step: :any, min: 0, class: 'form-control form-control-inline ingredient-price', placeholder: "Price", required: true, value: (number_with_precision(f.object.price, precision: 2)), title: "Price of pack"

      = f.number_field :size, step: :any, min: 0, class: 'form-control form-control-inline ingredient-size', placeholder: "Size", required: true, value: (number_with_precision(f.object.size, precision: 0)), title: "The size of the pack"

      = f.select :size_unit_of_measurement, [['g','g'],['kg','kg'],['ml','ml'],['l','l'],['oz','oz'],['lb','lb'],['tsp','tsp'],['tbsp','tbsp'],['pint','pint'],['each','unit']], {prompt: 'Unit'}, {required: 'true', autofocus: 'true', class: 'form-control form-control-inline dropdown', title: "Unit of measurement"}
      = link_to_remove_association '<i class="fa fa-times-circle fa-lg rotate"></i>'.html_safe, f
  br

app/views/recipes/_notes.html.slim
#notes
  h2 Notes
  - @notes.each do |note|
    .note
      = note.body
      = link_to '<i class="fa fa-times-circle fa-lg rotate"></i>'.html_safe, [note.recipe, note], data: { confirm: 'Are you sure?' }, method: :delete

= form_for([@recipe, @recipe.notes.build]) do |f|
  .form-group
    = f.text_area :body, placeholder: 'Add a note here'

    = f.submit 'Add note', class: 'button'

app/views/recipes/_recipes.html.slim
= hidden_field_tag :direction, params[:direction]
= hidden_field_tag :sort, params[:sort]


table.table
  tr
    th.hide Recipe name
    th.hide Total price
  - @recipes.each do |recipe|
    tr.first-row data-link=recipe_path(recipe.id)
      td.title-row = link_to recipe.name, recipe_path(recipe.id)
      td.text-right.cost-row = number_to_currency(recipe.cost.to_s, unit: "£")
    - if recipe.quantity?
      tr.quantity-row
        td.hint = "#{recipe.quantity.floor} servings"
        td.hint.text-right = "(#{number_to_currency(recipe.calculate_portion_cost, unit: "£")}/serving)"
    - else
      tr.quantity-row
        td.hint n/a
        td.hint.text-right n/a

app/views/recipes/edit.html.slim
= render 'form', button_text: 'Save'

app/views/recipes/index.html.slim
section.container

  h1 #{greeting} #{current_user.first_name}

  h2 #{personalised_message}
  .row
    .col-md-6.col-md-offset-3
      .link-container
        = link_to 'Add recipe', new_recipe_path, class: 'add-button button'

      - if @recipes.any?
        .recipes
          = render 'recipes'
      - else
        h2.no-recipe-warning Looks like you haven't added any recipes yet! Click add recipe to get started

  .bread
    = image_tag('Bread.png')

  .whisk
    = image_tag('whisk.png')

app/views/recipes/index.js.slim
| $(".recipes").html("
= escape_javascript(render 'recipes')
|");

app/views/recipes/new.html.slim
= render 'form', button_text: 'Create'

app/views/recipes/show.html.slim
section.container
  .row
    .col-md-6.col-md-offset-3
      h1.show-title = @recipe.name
      .cost-breakdown
        span
          | Cost: 
          = number_to_currency(@recipe.cost.to_s, unit: "£")
          br
        span.hint
          - if @recipe.quantity?
            = "(#{number_to_currency(@portion_cost, unit: "£")}/serving)"
          - else
            = link_to 'Add servings', recipe_path(@recipe.id, anchor: 'quantity-breakdown'), class: 'button'
      table.table
        tr
          th.hide Name
          th.hide Quantity
          th.hide Unit price
          th.hide Unit price per unit
        - @recipe.ingredients.each do |i|
          tr
            td.title-row = i.name
            td.text-right.title-row = "#{number_with_precision(i.amount, precision: 0)}#{i.amount_unit_of_measurement unless i.is_unit?}"
          tr
            td.hint = number_to_currency(i.unit_price, unit: "£")
            td.hint.text-right = "(#{number_to_currency(i.calculate_price_per_unit * 100, unit: "£", precision: i.determine_precision)}/100#{i.amount_unit_of_measurement unless i.is_unit?})"

      = render 'notes'

      .settings
        #quantity-breakdown
          = form_for @recipe do |f|
            .form-group
              = f.number_field :quantity, min: 0, class: 'form-control form-portion', value: number_with_precision(@recipe.quantity, precision: 0)


              = f.submit 'Update servings', class: 'button servings-button'

          .buttons
            = link_to 'Edit recipe', edit_recipe_path(@recipe), class: 'button edit-button'
            = link_to 'Delete recipe', recipe_path(@recipe.id), data: { confirm: 'Are you sure?' }, method: :delete, class: 'button delete-button'

  .bread-2
    = image_tag('Bread-2.png')

  .chocolate-2
    = image_tag('chocolate-2.png')