config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: "callbacks", registrations: 'users/registrations' }
  root 'welcome#index'

  resources :recipes do
    resources :notes
  end

  match 'search(/:search)', :to => 'recipes#index', :as => :search, via: [:get, :post]
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, :except => [:index]
  
  def index
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.slim
section.container
  span.title Bakewell

  .blurb.type-it

  .get-started
    = link_to 'Get started', recipes_path, class: 'button'

  = link_to '<i class="fa fa-chevron-down" aria-hidden="true"></i>'.html_safe, root_path(anchor: "intro-one"), class: 'chevron-anchor'

section.container id='intro-one'
  .row
    .col-md-8.col-md-offset-2
      p Bakewell is a an easy-to-use website, that lets you build up a library of recipes, calculating both the total cost and the cost per serving, and lets you save any additional information by adding notes.
      
      p It was inspired by, and created for my mum who loves to bake but finds recipe apps too complicated for her needs, and Excel spreadsheets not intuitive enough.

      br

      = image_tag('mum_baking.jpg', class: 'mum')
      p.hint Mum doing what she loves best

      .get-started
        = link_to 'Back to top', root_path(anchor: "header"), class: 'button'

.egg
  = image_tag('Egg-19.png')